language: go
go:
- 1.10.x
install:
- go get gopkg.in/alecthomas/gometalinter.v1
- go get github.com/gordonklaus/ineffassign
- go get github.com/jgautheron/goconst/cmd/goconst
- go get github.com/kisielk/errcheck
- go get github.com/golang/dep/cmd/dep
- dep ensure
script:
- gometalinter.v1 --vendor --disable-all --enable=vet --enable=ineffassign --enable=goconst
  --tests ./...
- go test -v -race ./...
before_script:
- echo "REPO $TRAVIS_REPO_SLUG TAG ${TRAVIS_TAG}"
before_deploy:
- go get github.com/goreleaser/goreleaser
deploy:
- provider: script
  script: goreleaser
  skip_cleanup: true
  on:
    tags: true
after_deploy:
- git clone https://github.com/sensu/sensu-go-bonsai-asset.git bonsai
- bonsai/generate-sha512sum.sh
- bonsai/github-release-upload.sh github_api_token=$GITHUB_TOKEN repo_slug="$TRAVIS_REPO_SLUG"
  tag="${TRAVIS_TAG}" filename="dist/$(cat dist/sha512_file)"
env:
  global:
    secure: Unn6Lrh2CelI0C4gD/fx2ZabxDrlTK3ovN8Vhl08tmZbD9AcxD/K3i/uJ+8+kRYayRhPoSVbRyk/Uak6J3Q8dcPPBiQ2l/05ZQnFSReYlt6MFQwaEAo+/U0r7s6JuFm/ekMop0mmwtg/UVWvhvEDf4k1gdKVg/nmYr2X0lQLuBkdWzHhcGJtWLB+kdew5HK7PUYbdkjccKUWycerkQ4emb3HqqFDvQfqgPzbjCJu29axxRvOk/wVy+L5rteo6GIOSsuvouhNEjxlLRff3s5aO+ABfuD+DQXP7dtRf0gSkwdlxR1d6hDGI7rE+uJFBNFRRqXf54COATYLSgR/9K1XJjSbuosscfN7e4D08MmC3H08+huj3Cs5tw24xNfMygoMyrjAIcvJBBgQSaY+tkWKD8fXAWlOYPERxJ3oYyVubzJxFFdLudWcg51Mlh3a4utjXX1r9RwmTfMRPzcfuGqJvHOm9EHqF9Pl4RGsoBfhSy2/NrJZmd7ua+1XImPhd7pwlYy9tV2vO0Yuuc7hd4ryB+AHZzlDsFTAySAH3vf5vH7UQrsrduhjD09J4r8l3Z90+v2jSwqoIpLAInqhtXIld+N9PRBez4BO6P7i/YKqOym0uZbSYjg28B8RbOY9qffK/REpMQ9bXUkXFl0k18E7bCw4HHyHqYD7ehxRDYObnuU=
